# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "numpy>=1.26",
#   "opencv-python-headless>=4.9",
# ]
# ///
"""Convert every frame of a video into ASCII art or a TypeScript module."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import cv2
import numpy as np


DEFAULT_WIDTH = 160
DEFAULT_HEIGHT = 58
DEFAULT_CHARSET = "@%#*+=-:. "
DEFAULT_CHARSET_HELP = DEFAULT_CHARSET.replace("%", "%%")
DEFAULT_TS_CONSTANT_NAME = "ASCII_VIDEO_FRAMES"
DEFAULT_TS_FPS = 24


def positive_int(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"{value!r} is not an integer") from exc

    if parsed <= 0:
        raise argparse.ArgumentTypeError("value must be greater than 0")
    return parsed


def frame_to_ascii(
    frame: np.ndarray,
    *,
    width: int,
    height: int,
    charset: str,
) -> str:
    resized = cv2.resize(frame, (width, height), interpolation=cv2.INTER_AREA)
    gray = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)

    scale = (len(charset) - 1) / 255
    indexes = np.rint(gray * scale).astype(np.int16)
    lines = ("".join(charset[index] for index in row) for row in indexes)
    return "\n".join(lines)


def default_output_path(input_path: Path) -> Path:
    return input_path.with_name(f"{input_path.stem}_ascii.txt")


def default_typescript_output_path(input_path: Path) -> Path:
    return input_path.with_name(f"{input_path.stem}_ascii.ts")


def typescript_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def write_text_frame(
    output_file,
    *,
    ascii_frame: str,
    frame_number: int,
    fps: float,
    total_frames: int,
    no_headers: bool,
) -> None:
    if frame_number:
        output_file.write("\n\n")

    if not no_headers:
        timestamp = frame_number / fps if fps else 0
        output_file.write(
            f"--- frame {frame_number + 1}"
            f"{f'/{total_frames}' if total_frames else ''}"
            f" time={timestamp:.3f}s ---\n"
        )

    output_file.write(ascii_frame)


def write_typescript_module(
    output_path: Path,
    *,
    frames: list[str],
    width: int,
    height: int,
    fps: int,
    constant_name: str,
) -> None:
    frame_values = ",\n".join(f"  {typescript_string(frame)}" for frame in frames)
    output_path.write_text(
        "\n".join(
            [
                "// This file is generated by scripts/video_to_ascii.py.",
                "",
                f"export const ASCII_VIDEO_WIDTH = {width} as const;",
                f"export const ASCII_VIDEO_HEIGHT = {height} as const;",
                f"export const ASCII_VIDEO_FPS = {fps} as const;",
                f"export const {constant_name} = [",
                frame_values,
                "] as const;",
                "",
                f"export type AsciiVideoFrame = (typeof {constant_name})[number];",
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert every frame of an MP4/video file to ASCII art.",
    )
    parser.add_argument("input", type=Path, help="Input video path, for example video.mp4")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output path. Defaults to <input>_ascii.txt or <input>_ascii.ts.",
    )
    parser.add_argument(
        "--format",
        choices=("txt", "ts"),
        default="txt",
        help="Output format. Use 'ts' to generate an importable TypeScript module.",
    )
    parser.add_argument(
        "--width",
        type=positive_int,
        default=DEFAULT_WIDTH,
        help=f"Output frame width in characters. Default: {DEFAULT_WIDTH}",
    )
    parser.add_argument(
        "--height",
        type=positive_int,
        default=DEFAULT_HEIGHT,
        help=f"Output frame height in characters. Default: {DEFAULT_HEIGHT}",
    )
    parser.add_argument(
        "--charset",
        default=DEFAULT_CHARSET,
        help=(
            "Characters from darkest to lightest. "
            f"Default: {DEFAULT_CHARSET_HELP!r}"
        ),
    )
    parser.add_argument(
        "--invert",
        action="store_true",
        help="Reverse the charset so light pixels use dense characters.",
    )
    parser.add_argument(
        "--no-headers",
        action="store_true",
        help="Write only ASCII frames, without frame/time separator headers.",
    )
    parser.add_argument(
        "--max-frames",
        type=positive_int,
        help="Stop after this many frames. Useful for quick tests.",
    )
    parser.add_argument(
        "--fps",
        type=positive_int,
        default=DEFAULT_TS_FPS,
        help=f"Playback FPS to export in TypeScript mode. Default: {DEFAULT_TS_FPS}",
    )
    parser.add_argument(
        "--constant-name",
        default=DEFAULT_TS_CONSTANT_NAME,
        help=(
            "Name of the exported frame array in TypeScript mode. "
            f"Default: {DEFAULT_TS_CONSTANT_NAME}"
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_path = args.input.expanduser().resolve()
    output_path = (
        args.output
        or (
            default_typescript_output_path(input_path)
            if args.format == "ts"
            else default_output_path(input_path)
        )
    ).expanduser().resolve()

    if not input_path.exists():
        print(f"Input video does not exist: {input_path}", file=sys.stderr)
        return 1

    charset = args.charset[::-1] if args.invert else args.charset
    if len(charset) < 2:
        print("Charset must contain at least two characters.", file=sys.stderr)
        return 1

    capture = cv2.VideoCapture(str(input_path))
    if not capture.isOpened():
        print(f"Could not open video: {input_path}", file=sys.stderr)
        return 1

    fps = capture.get(cv2.CAP_PROP_FPS) or 0
    total_frames = int(capture.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    frame_number = 0
    try:
        ts_frames: list[str] = []
        output_file = None
        if args.format == "txt":
            output_file = output_path.open("w", encoding="utf-8", newline="\n")

        try:
            while True:
                ok, frame = capture.read()
                if not ok:
                    break

                if args.max_frames is not None and frame_number >= args.max_frames:
                    break

                ascii_frame = frame_to_ascii(
                    frame,
                    width=args.width,
                    height=args.height,
                    charset=charset,
                )

                if args.format == "ts":
                    ts_frames.append(ascii_frame)
                else:
                    if output_file is None:
                        raise RuntimeError("Text output file is not open.")
                    write_text_frame(
                        output_file,
                        ascii_frame=ascii_frame,
                        frame_number=frame_number,
                        fps=fps,
                        total_frames=total_frames,
                        no_headers=args.no_headers,
                    )

                frame_number += 1

            if args.format == "ts":
                write_typescript_module(
                    output_path,
                    frames=ts_frames,
                    width=args.width,
                    height=args.height,
                    fps=args.fps,
                    constant_name=args.constant_name,
                )
        finally:
            if output_file is not None:
                output_file.close()
    finally:
        capture.release()

    if frame_number == 0:
        print("No frames were read from the video.", file=sys.stderr)
        return 1

    print(f"Wrote {frame_number} frame(s) to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
